export const AlertTextOptions = {
  "INCÊNDIO": [
        'Mantenha a calma:',
        'Desespero te torna uma menos produtiva e o fará pensar de forma arriscada, concentre-se em pensar de forma racional',
        'Procure uma forma de procurar ajuda:',
        'Caso o alarme de segurança da Fulltime não acione procure seu celular e chame os bombeiros utilizando o número 193, caso esteja sem seu celular, vá até um vizinho ou acione o alarme de incêndio de seu prédio/condomínio.',
        'Evacue Imediatamente:',
        'Saia do local que esteja em chamas imediatamente pela saída mais próxima.',
        'Caso more em prédio:',
        'Nunca use elevadores, eles podem parar de funcionar caso ocorra um corte de energia ou se tornarem uma espécie de chaminé para a fumaça.',
        'Verifique as portas:',
        'Sempre verifique as portas em caso de incêndio, se elas estiverem quentes o fogo está do outro lado dela, levando isso em consideração procure outra rota de fuga.',
        'Rasteje se houver fumaça:',
        'A fumaça soltada pelo fogo sobe e fica na altura de sua cabeça, procure andar abaixado para evitar inalação de fumaça, se possível cubra o nariz e a boca com um pano molhado.',
        'Feche as portas:',
        'Após passar pelos cômodos feche as portas sem trancar para retardar a propagação de fogo e fumaça. ',
        'Fique a uma distância segura:',
        'Vá até o ponto de encontro designado caso more em condomínio ou prédio ou se afaste e vá para um local seguro longe do incêndio.'
  ],
  "ALAGAMENTO": [
        'Evite atravessar áreas alagadas:',
        'Mesmo que a água pareça rasa, seu olhar pode ser facilmente enganado pela ilusão de profundidade causada pela água, o mais correto a fazer é evitar passar por locais com muita água.',
        'Procure locais altos:',
        'Procurar lugares altos ou andares superiores é uma forma viável de evitar contato com a água.',
        'Desligue imediatamente o disjuntor geral:',
        'Para evitar tomar choques, é recomendado que desligue a chave geral de energia de sua casa para tornar o ambiente mais seguro.',
        'Evite ficar próximo de locais com eletricidade:',
        'Afaste-se de tomadas, fios e aparelhos molhados para evitar de tomar uma descarga de energia.',
        'Proteja pertences importantes:',
        'Guarde coisas de importância e de mais relevância em sacos impermeáveis.',
        'Nunca deixe crianças brincar na água:',
        'Busque evitar deixar crianças próximas da água pois ela pode estar contaminada.',
        'Se estiver de carro:',
        'Não atravesse vias inundadas (a correnteza pode arrastar o veículo).',
        'Após o alagamento:',
        'Use luvas e botas para limpeza.',
        'Descarte alimentos e itens contaminados.',
        'Solicite vistoria elétrica antes de religar a energia.'
  ],
  "FURTO/ROUBO RESIDENCIAL": [
        'Se o ladrão estiver no local:',
        'Não reaja.',
        'Mantenha movimentos lentos.',
        'Priorize proteger vidas.',
        'Tente se afastar e acione a polícia (190) discretamente.',
        'Se chegar em casa e perceber sinais de arrombamento:',
        'Não entre.',
        'Afaste-se e ligue imediatamente para a polícia.',
        'Após a ocorrência:',
        'Registre BO.',
        'Tire fotos dos danos (sem mexer em nada).',
        'Liste objetos furtados.',
        'Reforce a segurança:',
        'Instalar trancas, câmeras, iluminação externa.'
  ],
  "EMERGÊNCIA MÉDICA": [
        'Mantenha a calma:',
        'Controle suas emoções, caso a vítima tenha passado mal verifique se ela está consciente.',
        'Procure por ajuda:',
        'A vítima precisa de cuidados de médicos da área de sua emergência médica para que você faça os procedimentos corretos para mantê-la segura e consciente. Ligue para o 192 e explique a situação com clareza e pergunte o que fazer nessa situação.',
        'Vítima não está conseguindo respirar:',
        'Caso a vítima não esteja conseguindo respirar começe a fazer RCP (compressões em seu tórax).Continue até a chegada de socorro ou até a vítima reagir.',
        'Se houver sangramento:',
        'Aplique pressão direta com pano limpo ou gaze. Mantenha o membro lesionado elevado, se possível.',
        'Em convulsões:',
        'Não segure a vítima. Mantenha a cabeça protegida com uma peça de roupa. Afaste objetos ao redor.',
        'Não dê alimentos, bebidas ou remédios:',
        'Não ofereça nada para a vítima, principalmente se a vítima estiver inconsciente.',
        'Acompanhe a vítima:',
        'Acompanhe a vítima da emergência até a chegada de profissionais qualificados.'
  ],
  "FALHA NA ILUMINAÇÃO": [
        'Use lanternas:',
        'Priorize em evitar usar velas para prevenir incêndios.',
        'Tire Eletrodomésticos da tomada:',
        'Desligue ou desconecte eletrodomésticos para evitar queima quando a energia voltar.',
        'Verifique o quadro de energia:',
        'Para confirmar se o problema não é interno, verifique o quadro de luz de sua residência.',
        'Evite locais escuros:',
        'Evite circular em escadas ou áreas escuras sem iluminação adequada.',
        'Alimentos de geladeira:',
        'Mantenha as portas da geladeira fechadas para conservar alimentos.',
        'Observe os sinais:',
        'Fique atento a ruídos ou odores de queimado; nesse caso, mantenha tudo desligado e aguarde o eletricista.',
        'Converse com profissionais:',
        'Comunique a companhia de energia caso a falha seja prolongada.'
  ],
  "PÂNICO": [
        'Busque um ambiente tranquilo:',
        'Leve a pessoa a um ambiente calmo e fresco.',
        'Incentive respiração lenta:',
        'Inspire pelo nariz por 4 segundos.',
        'Segure 2 segundos.',
        'Expire pela boca por 6 segundos.',
        'Fale com calma:',
        'Fale em tom calmo, com frases objetivas como “Você está seguro, vamos respirar juntos.”',
        'Evite manifestações:',
        'Afaste curiosos para reduzir a pressão emocional.',
        'Leve a situação a sério:',
        'Não minimize a crise dizendo “é frescura” ou “pare com isso”.',
        'Mantenha atenção:',
        'Se a crise durar mais de 20 minutos, houver dor no peito ou desmaio, acione o SAMU (192).',
        'Recomende ajuda a pessoa:',
        'Após a crise, recomende acompanhamento psicológico ou psiquiátrico.'
  ],
  "CHUVAS SEVERAS": [
        'Permaneça em local seguro:',
        'Evite deslocamentos desnecessários e vá para locais onde seja seguro.',
        'Feche portas e janelas:',
        'Fechar portas e janelas é necessário para evitar entrada de vento e água.',
        'Desconecte eletroeletrônicos:',
        'Desconectar eletrônicos é importante nesses casos, especialmente em chuva de raios.',
        'Evite contato com estruturas metálicas:',
        'Estruturas metálicas costumam atrair raios durante tempestades e evitá-las previne você de ser atingido por um desses raios.',
        'Não se abrigue sob árvores:',
        'Árvores parecem ser locais seguros em tempestades, porém é o completo oposto pois aumentam o risco de queda e descargas elétricas.',
        'Se estiver dirigindo:',
        'Reduza a velocidade, mantenha faróis baixos ligados, evite atravessar poças profundas',
        'Se houver risco de deslizamento:',
        'Se houver risco de deslizamento saia do veículo e procure abrigo seguro.',
        'Monitores de alertas da Defesa Civil:',
        'Se receber um tipo de mensagem de alerta em seu celular de chuvas severas, observe o alerta e siga as instruções dadas pelo governo'
  ],
  "VIOLÊNCIA DOMÉSTICA": [
        'Procure ajuda:',
        'Priorize a segurança: tente sair do ambiente onde há ameaça e contate a polícia (190) ou o Disque 180.',
        'Evite confronto:',
        'Não confronte o agressor, especialmente se ele estiver armado ou alterado.',
        'Procure um local mais seguro:',
        'Busque abrigo seguro em casa de familiares, amigos ou instituições especializadas.',
        'Vá a justiça:',
        'Registre o boletim de ocorrência imediatamente.',
        'Tenha provas:',
        'Guarde mensagens, fotos de ferimentos e relatos de testemunhas.',
        'Busque por um médico:',
        'Procure atendimento médico mesmo para ferimentos leves.',
        'Consiga testemunhas:',
        'Testemunhar violência, não intervenha fisicamente; chame a polícia.'
  ],
  "SUPERVISÃO": [
        'Pessoas selecionadas:',
        'Defina claramente os responsáveis pela supervisão do ambiente ou das pessoas.',
        'Realize Inspeções:',
        'Inspeções regulares são importantes para identificar riscos (buracos, fiações expostas, objetos perigosos).',
        'Converse com moradores:',
        'Mantenha comunicação constante entre supervisores e responsáveis.',
        'Faça regras:',
        'Estabeleça regras claras de comportamento seguro e explique-as aos supervisionados.',
        'Observe atitudes suspeitas:',
        'Intervenha imediatamente ao detectar atitudes inseguras.',
        'Documente incidentes:',
        'Reporte para responsáveis ou gestores.',
        'Procure Melhorias:',
        'Implemente melhorias preventivas com base nas ocorrências registradas.'
  ]
};